testing/testing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('topics.urls', namespace='topics')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

testing/topics/urls.py
from . import views
from django.urls import path, re_path


app_name = 'topics'
urlpatterns = [
    path('', views.index, name='group_list'),
    path('group/<slug:slug>/', views.tests_in_group, name='tests_in_group'),
    path('tests/<int:test_id>/', views.test_detail, name='test_detail'),
    path('tests/<int:test_id>/<int:question_id>/', views.question_detail, name='question_detail'),
    path('result/', views.results, name='results')
]

testing/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
]

testing/core/models.py
from django.db import models

# Create your models here.

testing/topics/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()





class Group(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название группы тестов')
    description = models.CharField(max_length=50, verbose_name='Описание группы')
    slug = models.SlugField(unique=True, verbose_name='URL-ярлык')

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'Набор тестов'
        verbose_name_plural = 'Наборы тестов'


class Test(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название теста')
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups',
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'


class Question(models.Model):
    test = models. ForeignKey(
        Test,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='tests',
    )
    name = models.TextField(verbose_name='Вопрос')

    def __str__(self) -> str:
        return self.name

    # def next_question(self, test_id):
    #     next_question = Question.objects.filter(test_id=test_id, id__gt=self.id).order_by('id').first()
    #     if next_question:
    #         return reverse('test_detail', kwargs={'test_id': test_id, 'id': next_question.id})

    def get_next(self):
        return Question.objects.filter(id__gt=self.id).order_by('id').first()

    class Meta:
        ordering = ['id']
        verbose_name_plural = 'Вопросы'


class Answer(models.Model):
    name = models.CharField(max_length=150, verbose_name='Вариант ответа')
    question = models.ForeignKey(
        Question,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='answers',
    )
    check = models.BooleanField(default=False, verbose_name="Правильный ответ")

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = 'Ответы'


class UserTest(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user',
        verbose_name='Пользователь',
    )
    test = models.ForeignKey(
        Test,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='user_tests',
    )
    right_answers = models.IntegerField(default=0)
    wrong_answers = models.IntegerField(default=0)

testing/topics/forms.py
from django import forms
from .models import Group, Test, Question, Answer


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ('name', 'group')


class AnswerForm(forms.Form):
    answer_check = forms.BooleanField(required=False)

    def clean_post(self):
        data = self.cleaned_data['answer_check']
        if data is False:
            raise forms.ValidationError('Выберите один вили несколько вариантов ответа')
        return data

testing/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

testing/core/views.py
from django.shortcuts import render

# Create your views here.

testing/topics/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Test, Group, Question, UserTest
NUMBER_OF_POSTS: int = 10


def index(request):
    template = 'topics/index.html'
    group_list = Group.objects.all()
    paginator = Paginator(group_list, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def test_detail(request, test_id):
    template = 'topics/test.html'
    test = get_object_or_404(Test, id=test_id)
    question = Question.objects.filter(test_id=test.id).first()
    context = {
        'test': test,
        'question': question,
    }
    return render(request, template, context)


@login_required
def question_detail(request, test_id, question_id):
    template = 'topics/questions.html'
    test = get_object_or_404(Test, id=test_id)
    question_ids = Question.objects.filter(test_id=test.id).values_list('id', flat=True)
    if question_id in question_ids:
        question = get_object_or_404(Question, id=question_id)
        context = {
            'test': test,
            'question': question,
            'question_ids': question_ids,
        }
        #answers = Answer.objects.filter(question_id=question_id).values_list('name', 'check')
        answers = question.answers.values_list('name', 'check')
        right_list = []
        for answer in answers:
            if answer[1] is True:
                right_list.append(answer[0])
        print(right_list)
        right_answers = 0
        wrong_answers = 0
        if request.method == "POST":
            check_list = request.POST.getlist('check')
            result = UserTest.objects.create(user=request.user, test_id=test_id)
            if check_list:
                if check_list == right_list:
                    print("Да!")
                    result.right_answers += 1
                else:
                    print("Нет!")
                    result.wrong_answers += 1
                    result.save()
                return render(request, template, context)
            else:
                context['error_message'] = 'Выберите один или несколько вариантов ответа'
                return render(request, template, context)
        return render(request, template, context)
    return render(request, 'topics/result.html')


@login_required
def tests_in_group(request, slug):
    template = 'topics/tests_in_group.html'
    group = get_object_or_404(Group, slug=slug)
    tests_list = group.groups.all()
    paginator = Paginator(tests_list, NUMBER_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, template, context)


def results(request, test_id):
    result = UserTest.objects.filter(user=request.user, test_id=test_id)
    return render(request, 'topics/result.html', {'result': result})

testing/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

testing/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
        <meta name="msapplication-TileColor" content="#000">
        <meta name="theme-color" content="#ffffff">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">  
        <title>
        {% block title %}
          Пусто
        {% endblock %}
        </title>               
    </head>
    <body>
        <header>
            {% include 'includes/header.html' %}
        </header>       
        <main> 
          <div class="container">
          <br>
          {% block content %}      
            Пусто!
          {% endblock %}
          </div>
        </main>
        <footer class="border-top text-center py-3">
            {% include 'includes/footer.html' %}
        </footer>
    </body>
</html>

testing/templates/includes/footer.html
<p>_________________________</p>

testing/templates/includes/header.html
    <div class="container">
      {% with request.resolver_match.view_name as view_name %}
      <ul>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'topics:group_list' %}active{% endif %}"
            href="{% url 'topics:group_list' %}">Все тесты</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name == 'users:password_reset_form' %}active{% endif %}"
            href="{% url 'users:password_reset_form' %}">Изменить пароль</a>
          </li>
          <li class="nav-item">
          <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}"
          href="{% url 'users:logout' %}">Выйти</a>
        </li>
          <li>
                  Пользователь: {{ user.username }}
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}"
            href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}"
            href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>

  

testing/templates/topics/index.html
{% extends 'base.html' %}
{% block title %}Список тем для тестирования{% endblock %}
{% block content %}
{% load user_filters %}
  <h1>Наборы тестов: </h1>
  {% for group in page_obj %}
  <article>
      <ul>
          <h3>
            <a href="{% url 'topics:tests_in_group' group.slug %}">
                {{ group.title }}
            </a>
          </h3>
      </ul>
  </article>
  {% endfor %}
{% endblock %}

testing/templates/topics/questions.html
{% extends 'base.html' %}
{% block title %}{{ test.name }}{% endblock %}
{% block content %}
{% load user_filters %}
  <div>
      <ul>
          <h4>{{ test.name }}</h4>
      </ul>

      <ul>
          {% if error_message %}<p><strong>{{ error_message }}</strong></p> {% endif %}
              <form action="{% url 'topics:question_detail' test.id question.get_next.id %}" method="post">
              {% csrf_token %}
                     <p>Вопрос: {{ question.name }}</p>
                      <p>Варианты ответов:</p>
                      {% for answer in question.answers.all %}

                        <p><input type="checkbox" value={{answer.name}} name="check">{{ answer.name }}</p>
                      {% endfor %}
                  <input type="submit" value="Следующий вопрос">

              </form>
      </ul>
  </div>
{% endblock %}

testing/templates/topics/result.html
{% extends 'base.html' %}
{% block title %}Результат{% endblock %}
{% block content %}
{% load user_filters %}
<ul>
    Правильных ответов: {{ result.right_answers }}
</ul>
<ul>
    Неправильных ответов: {{ result.wrong_answers }}
</ul>
{% endblock %}

testing/templates/topics/test.html
{% extends 'base.html' %}
{% block title %}{{ test.name }}{% endblock %}
{% block content %}
{% load user_filters %}
  <div>
      <ul>
          <h3>{{ test.name }}</h3>
      </ul>
      <ul>
          <h2><a href="{% url 'topics:question_detail' test.id question.id %}"> Начать тест </a></h2>
      </ul>
  </div>
{% endblock %}

testing/templates/topics/tests_in_group.html
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
{% load user_filters %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  <hr>
  {% for test in page_obj %}
    <article>
        <ul>
            <li>
                <a href="{% url 'topics:test_detail' test.id %}">
                  {{ test.name }}
                </a>
            </li>
        </ul>
    <article>
  {% endfor %}
{% endblock %}

testing/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

testing/templates/users/login.html
{% extends 'base.html' %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row --> 
{% endblock %}

testing/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Восстановление пароля{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body"> 
          <form method="post" action="{% url 'users:password_reset_form' %}">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_email">
                Адрес электронной почты
                <span class="required text-danger">*</span>
              </label>    
              <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>  
</div>
{% endblock %}

testing/templates/users/signup.html
{% extends 'base.html' %}
{% block title %}Зарегистрироваться{% endblock title %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Зарегистрироваться
      </div>
      <div class="card-body">
      {% load user_filters %}
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <div class="alert alert-danger">
                {{ error|escape}}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape}}
          </div>
          {% endfor %}
        {% endif %}

        <form method='post' action="{% url 'users:signup' %}">
        {% csrf_token %}

        {% for field in form %}
          <div class="form-group row my-3 p-3">
            <label for="{{ field.id_for_label}}">
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
            </label>
            {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small
                  id="{{ field.id_for_label }}--help"
                  class="form-text text-muted"
                >
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
          </div>
        {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type='submit' class="btn btn-primary">
              Зарегистрироваться
            </button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock  %}